export const AUDIO_FILE_TYPES = [
    'audio/mpeg',
    'audio/wav',
    'audio/ogg',
    'audio/aac',
    'audio/flac',
    'audio/webm',
    'audio/x-wav',
    '.mp3',
    '.wav',
    '.ogg',
    '.aac',
    '.flac',
    '.webm',
].join(',');
